### ISSUE TITLE
Duplicate Projects breaks Projects.get_or_insert

### ISSUE THREAD

**Issue by jeffweiss** [elixirschool/extracurricular#29]
# Overview
Because we don't have any uniqueness constraints on Projects themselves, we can (through existing race conditions, but also just calls to `Projects.insert`) end up with multiple versions of the "same" Project but different ids. This completely breaks any later calls to `Projects.get` or `Projects.get_or_insert`. This ends up effectively denial of servicing issue processing for that entire project until someone manually intervenes.

## Example Race Condition
Let's suppose we have two issue payloads for the same (net new) project that come in at the same time with the following interleaving:
```
Issue A             Issue B
   |                   |
create                 |        
   |                create 
process_issue          |
   |              process_issue
get_or_insert          |
   |               get_or_insert
get -> nil             |
   |               get -> nil
insert                 |
                    insert
```

## Steps to Reproduce
```
iex> Data.Projects.insert(%{url: "https://wat.com", name: "blerg"})
iex> Data.Projects.insert(%{url: "https://wat.com", name: "blerg"})
iex> Data.Projects.get_or_insert(%{url: "https://wat.com", name: "blerg"})
```
## Expected Outcome
```
iex> Data.Projects.insert(%{url: "https://wat.com", name: "blerg"})
iex> Data.Projects.insert(%{url: "https://wat.com", name: "blerg"})
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: projects_pkey

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

    (ecto) lib/ecto/repo/schema.ex:495: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/schema.ex:481: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
iex> Data.Projects.get_or_insert(%{url: "https://wat.com", name: "blerg"})
{:ok, %Data.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, id: 1,
  inserted_at: ~N[2017-08-25 17:48:47.308797], name: "blerg", tags: [],
  updated_at: ~N[2017-08-25 17:48:47.308818], url: "https://wat.com"}}
```

## Actual Outcome
```
iex> Data.Projects.insert(%{url: "https://wat.com", name: "blerg"})
iex> Data.Projects.insert(%{url: "https://wat.com", name: "blerg"})
iex> Data.Projects.get_or_insert(%{url: "https://wat.com", name: "blerg"})
** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from p in Data.Project,
  where: p.name == ^"blerg" and p.url == ^"https://wat.com"

    (ecto) lib/ecto/repo/queryable.ex:71: Ecto.Repo.Queryable.one/4
    (data) lib/data/projects.ex:13: Data.Projects.get_or_insert/1
```

**Comment by doomspork** [comment]
@jeffweiss is the 💣 , thanks for catching this _and_ for participating in the project ❤️ 

We should most certainly have a database uniqueness constraint and then add that to the changesets.  Would you like to take a stab at this?  If you've got any questions myself, @ybur-yug, or any of the other @elixirschool/developers would be happy to help 😁

**Comment by jeffweiss** [comment]
@doomspork it's a thing that I came across while adding some [property based tests](http://propertesting.com), which revealed other bugs too, which I'll submit in between actual work. :joy: 

I'm gonna keep at the PBT and let @ybur-yug pair w/ other folks from the community to fix them (for now at least).

**Comment by doomspork** [comment]
Great @jeffweiss!  I'm sure we're going to turn up lots of little bugs here and there given the number of people participating (or hopefully participating), skill levels involved, and evolving features/enhancements.  Getting things well tested will be hugely beneficial 👍

**Comment by doomspork** [comment]
This was fixed by @dberget 💜

**Comment by jeffweiss** [comment]
I looked at the patch on #31, and it does indeed fix _part_ of the problem. 
The race condition still exists, but now instead of all future issues for that project being hosed it's just Issue B in the scenario above.
There are a couple ways to handle this: retry `get_or_insert` if you get a unique key constraint error (which you could still totally get btw since we get_by both name and URL but the constraint is just for URL) or synchronize/serialize certain parts of Project operations (if you're concerned about bottleneck in a single process, you could create a pool and then decide which to call by using something like [:erlang.phash2/2](http://erldocs.com/current/erts/erlang.html?i=1&search=Phas#phash2/2) ).

**Comment by doomspork** [comment]
We're going to be adding the majority (if not all) projects manually so we should never run into this situation.  If anything, we may want to consider removing the functionality since it isn't currently needed.

Thanks @jeffweiss!
